spring:
  datasource:
      url: jdbc:mysql://localhost:3306/room?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 28416107
mybatis:
   mapperLocations: classpath:/mapper/*.xml
   configuration:
       map-underscore-to-camel-case: true
server:
  port: 8888